module.exports = {
    SITE_ADMIN_ROLE: 'SITE_ADMIN_ROLE',
    GYM_ADMIN_ROLE: 'GYM_ADMIN_ROLE',
    GYM_MANAGER_ROLE: 'GYM_MANAGER_ROLE',
    GYM_COACH_ROLE: 'GYM_COACH_ROLE',
    ATHLETE_ROLE: 'ATHLETE_ROLE',
}