exports.emailMethods = {
    RESET_PASSWORD: 'RESET_PASSWORD',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    EMAIL_ACTIVATION: 'EMAIL_ACTIVATION',
}

exports.smsMethods = {
    LOGIN_CONFIRM: 'LOGIN_CONFIRM',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
}